// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(HaberContext))]
    [Migration("20260124012243_InitialPostgresMigration")]
    partial class InitialPostgresMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Haberler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("boolean")
                        .HasColumnName("AKTIF_MI");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BASLIK");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EKLEME_TARIHI");

                    b.Property<int>("GosterimSayisi")
                        .HasColumnType("integer")
                        .HasColumnName("GOSTERIM_SAYISI");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ICERIK");

                    b.Property<int>("KategoriId")
                        .HasColumnType("integer")
                        .HasColumnName("CATEGORY_ID");

                    b.Property<string>("Resim")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RESIM");

                    b.Property<string>("Video")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("VIDEO");

                    b.Property<int>("YazarId")
                        .HasColumnType("integer")
                        .HasColumnName("YAZAR_ID");

                    b.HasKey("Id");

                    b.ToTable("HABERLER");
                });

            modelBuilder.Entity("Domain.Entities.Kategoriler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ACIKLAMA");

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("boolean")
                        .HasColumnName("AKTIF_MI");

                    b.HasKey("Id");

                    b.ToTable("KATEGORILER");
                });

            modelBuilder.Entity("Domain.Entities.Slaytlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("boolean")
                        .HasColumnName("AKTIF_MI");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BASLIK");

                    b.Property<int>("HaberId")
                        .HasColumnType("integer")
                        .HasColumnName("HABER_ID");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ICERIK");

                    b.Property<string>("Resim")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RESIM");

                    b.HasKey("Id");

                    b.ToTable("SLAYTLAR");
                });

            modelBuilder.Entity("Domain.Entities.Yazarlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("AD");

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("boolean")
                        .HasColumnName("AKTIF_MI");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EPOSTA");

                    b.Property<string>("Resim")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RESIM");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("SIFRE");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("SOYAD");

                    b.HasKey("Id");

                    b.ToTable("YAZARLAR");
                });

            modelBuilder.Entity("Domain.Entities.Yorumlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("AD");

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("boolean")
                        .HasColumnName("AKTIF_MI");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BASLIK");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EKLEME_TARIHI");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EPOSTA");

                    b.Property<int>("HaberId")
                        .HasColumnType("integer")
                        .HasColumnName("HABER_ID");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ICERIK");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("SOYAD");

                    b.HasKey("Id");

                    b.ToTable("YORUMLAR");
                });
#pragma warning restore 612, 618
        }
    }
}
