// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(HaberContext))]
    [Migration("20260126231330_AddBlogModule")]
    partial class AddBlogModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.BlogKategoriler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ACIKLAMA");

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ADI");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean")
                        .HasColumnName("AKTIF_MI");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("OLUSTURMA_TARIHI");

                    b.Property<int>("Sira")
                        .HasColumnType("integer")
                        .HasColumnName("SIRA");

                    b.HasKey("Id");

                    b.ToTable("BLOG_KATEGORILER");
                });

            modelBuilder.Entity("Domain.Entities.BlogYorumlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("AD");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean")
                        .HasColumnName("AKTIF_MI");

                    b.Property<int>("BlogId")
                        .HasColumnType("integer")
                        .HasColumnName("BLOG_ID");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("EPOSTA");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("OLUSTURMA_TARIHI");

                    b.Property<bool>("OnaylandiMi")
                        .HasColumnType("boolean")
                        .HasColumnName("ONAYLANDI_MI");

                    b.Property<string>("Soyad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("SOYAD");

                    b.Property<string>("Yorum")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("YORUM");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.ToTable("BLOG_YORUMLAR");
                });

            modelBuilder.Entity("Domain.Entities.Bloglar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean")
                        .HasColumnName("AKTIF_MI");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("BASLIK");

                    b.Property<string>("Etiketler")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ETIKETLER");

                    b.Property<string>("GorselUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("GORSEL_URL");

                    b.Property<int>("GoruntulenmeSayisi")
                        .HasColumnType("integer")
                        .HasColumnName("GORUNTULEME_SAYISI");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("GUNCELLENME_TARIHI");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ICERIK");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("integer")
                        .HasColumnName("KATEGORI_ID");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("OLUSTURMA_TARIHI");

                    b.Property<string>("Ozet")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("OZET");

                    b.Property<DateTime>("YayinTarihi")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("YAYIN_TARIHI");

                    b.Property<int?>("YazarId")
                        .HasColumnType("integer")
                        .HasColumnName("YAZAR_ID");

                    b.HasKey("Id");

                    b.HasIndex("AktifMi");

                    b.HasIndex("KategoriId");

                    b.HasIndex("YazarId");

                    b.ToTable("BLOGLAR");
                });

            modelBuilder.Entity("Domain.Entities.Haberler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("boolean")
                        .HasColumnName("AKTIF_MI");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BASLIK");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("EKLEME_TARIHI");

                    b.Property<int>("GosterimSayisi")
                        .HasColumnType("integer")
                        .HasColumnName("GOSTERIM_SAYISI");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ICERIK");

                    b.Property<int>("KategoriId")
                        .HasColumnType("integer")
                        .HasColumnName("CATEGORY_ID");

                    b.Property<string>("Resim")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RESIM");

                    b.Property<string>("Video")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("VIDEO");

                    b.Property<int>("YazarId")
                        .HasColumnType("integer")
                        .HasColumnName("YAZAR_ID");

                    b.HasKey("Id");

                    b.ToTable("HABERLER");
                });

            modelBuilder.Entity("Domain.Entities.Kategoriler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ACIKLAMA");

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("boolean")
                        .HasColumnName("AKTIF_MI");

                    b.HasKey("Id");

                    b.ToTable("KATEGORILER");
                });

            modelBuilder.Entity("Domain.Entities.KullaniciRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtanmaTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ATANMA_TARIHI");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer")
                        .HasColumnName("KULLANICI_ID");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("ROL_ID");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId", "RolId")
                        .IsUnique();

                    b.ToTable("KULLANICI_ROLLER");
                });

            modelBuilder.Entity("Domain.Entities.Kullanicilar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("AD");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean")
                        .HasColumnName("AKTIF_MI");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("EPOSTA");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("OLUSTURMA_TARIHI");

                    b.Property<string>("Resim")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("RESIM");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("SIFRE_HASH");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SON_GIRIS_TARIHI");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("SOYAD");

                    b.HasKey("Id");

                    b.HasIndex("Eposta")
                        .IsUnique();

                    b.ToTable("KULLANICILAR");
                });

            modelBuilder.Entity("Domain.Entities.Roller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ACIKLAMA");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean")
                        .HasColumnName("AKTIF_MI");

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ROL_ADI");

                    b.HasKey("Id");

                    b.ToTable("ROLLER");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Sistem yöneticisi - tüm yetkiler",
                            AktifMi = true,
                            RolAdi = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "İçerik editörü - haber ve kategori yönetimi",
                            AktifMi = true,
                            RolAdi = "Editor"
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Yazar - kendi haberlerini yönetir",
                            AktifMi = true,
                            RolAdi = "Yazar"
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Moderatör - yorum moderasyonu",
                            AktifMi = true,
                            RolAdi = "Moderator"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Slaytlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("boolean")
                        .HasColumnName("AKTIF_MI");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BASLIK");

                    b.Property<int>("HaberId")
                        .HasColumnType("integer")
                        .HasColumnName("HABER_ID");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ICERIK");

                    b.Property<string>("Resim")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RESIM");

                    b.HasKey("Id");

                    b.ToTable("SLAYTLAR");
                });

            modelBuilder.Entity("Domain.Entities.Yazarlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("AD");

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("boolean")
                        .HasColumnName("AKTIF_MI");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EPOSTA");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("integer")
                        .HasColumnName("KULLANICI_ID");

                    b.Property<string>("Resim")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RESIM");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("SIFRE");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("SOYAD");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("YAZARLAR");
                });

            modelBuilder.Entity("Domain.Entities.Yorumlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("AD");

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("boolean")
                        .HasColumnName("AKTIF_MI");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BASLIK");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EKLEME_TARIHI");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EPOSTA");

                    b.Property<int>("HaberId")
                        .HasColumnType("integer")
                        .HasColumnName("HABER_ID");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ICERIK");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("SOYAD");

                    b.HasKey("Id");

                    b.ToTable("YORUMLAR");
                });

            modelBuilder.Entity("Domain.Entities.BlogYorumlar", b =>
                {
                    b.HasOne("Domain.Entities.Bloglar", "Blog")
                        .WithMany("Yorumlar")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("Domain.Entities.Bloglar", b =>
                {
                    b.HasOne("Domain.Entities.BlogKategoriler", "Kategori")
                        .WithMany("Bloglar")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.Kullanicilar", "Yazar")
                        .WithMany()
                        .HasForeignKey("YazarId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kategori");

                    b.Navigation("Yazar");
                });

            modelBuilder.Entity("Domain.Entities.BlogKategoriler", b =>
                {
                    b.Navigation("Bloglar");
                });

            modelBuilder.Entity("Domain.Entities.Bloglar", b =>
                {
                    b.Navigation("Yorumlar");
                });
#pragma warning restore 612, 618
        }
    }
}
