// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(HaberContext))]
    partial class HaberContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shared.Entities.Haberler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit")
                        .HasColumnName("AKTIF_MI");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BASLIK");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("EKLEME_TARIHI");

                    b.Property<int>("GosterimSayisi")
                        .HasColumnType("int")
                        .HasColumnName("GOSTERIM_SAYISI");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ICERIK");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int")
                        .HasColumnName("CATEGORY_ID");

                    b.Property<string>("Resim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RESIM");

                    b.Property<string>("Video")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VIDEO");

                    b.Property<int>("YazarId")
                        .HasColumnType("int")
                        .HasColumnName("YAZAR_ID");

                    b.HasKey("Id");

                    b.ToTable("HABERLER");
                });

            modelBuilder.Entity("Shared.Entities.Kategoriler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ACIKLAMA");

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit")
                        .HasColumnName("AKTIF_MI");

                    b.HasKey("Id");

                    b.ToTable("KATEGORILER");
                });

            modelBuilder.Entity("Shared.Entities.Slaytlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit")
                        .HasColumnName("AKTIF_MI");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BASLIK");

                    b.Property<int>("HaberId")
                        .HasColumnType("int")
                        .HasColumnName("HABER_ID");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ICERIK");

                    b.Property<string>("Resim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RESIM");

                    b.HasKey("Id");

                    b.ToTable("SLAYTLAR");
                });

            modelBuilder.Entity("Shared.Entities.Yazarlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AD");

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit")
                        .HasColumnName("AKTIF_MI");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EPOSTA");

                    b.Property<string>("Resim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RESIM");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SIFRE");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SOYAD");

                    b.HasKey("Id");

                    b.ToTable("YAZARLAR");
                });

            modelBuilder.Entity("Shared.Entities.Yorumlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AD");

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit")
                        .HasColumnName("AKTIF_MI");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BASLIK");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("EKLEME_TARIHI");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EPOSTA");

                    b.Property<int>("HaberId")
                        .HasColumnType("int")
                        .HasColumnName("HABER_ID");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ICERIK");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SOYAD");

                    b.HasKey("Id");

                    b.ToTable("YORUMLAR");
                });
#pragma warning restore 612, 618
        }
    }
}
