FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["HaberSitesi.sln", "./"]
COPY ["ApiUI/ApiUI.csproj", "ApiUI/"]
COPY ["Business/Business.csproj", "Business/"]
COPY ["DataAccess/DataAccess.csproj", "DataAccess/"]
COPY ["Shared/Shared.csproj", "Shared/"]
COPY ["ApiAccess/ApiAccess.csproj", "ApiAccess/"]

COPY ["AdminUI/AdminUI.csproj", "AdminUI/"]
COPY ["WebUI/WebUI.csproj", "WebUI/"]

RUN dotnet restore "ApiUI/ApiUI.csproj"

COPY . .
WORKDIR "/src/ApiUI"
RUN dotnet build "ApiUI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ApiUI.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ApiUI.dll"]
