-- HaberSitesi Database Migration Script
-- SQL Server 2022 / SQL Server Express
-- Generated: 2026-01-23

USE HABER_SITESI;
GO

-- Drop tables if exist (for clean install)
IF OBJECT_ID('YORUMLAR', 'U') IS NOT NULL DROP TABLE YORUMLAR;
IF OBJECT_ID('SLAYTLAR', 'U') IS NOT NULL DROP TABLE SLAYTLAR;
IF OBJECT_ID('HABERLER', 'U') IS NOT NULL DROP TABLE HABERLER;
IF OBJECT_ID('YAZARLAR', 'U') IS NOT NULL DROP TABLE YAZARLAR;
IF OBJECT_ID('KATEGORILER', 'U') IS NOT NULL DROP TABLE KATEGORILER;
IF OBJECT_ID('__EFMigrationsHistory', 'U') IS NOT NULL DROP TABLE __EFMigrationsHistory;
GO

-- Create EF Core Migrations History Table
CREATE TABLE __EFMigrationsHistory (
    MigrationId NVARCHAR(150) NOT NULL,
    ProductVersion NVARCHAR(32) NOT NULL,
    CONSTRAINT PK___EFMigrationsHistory PRIMARY KEY (MigrationId)
);
GO

-- KATEGORILER (Categories)
CREATE TABLE KATEGORILER (
    ID INT IDENTITY(1,1) NOT NULL,
    ACIKLAMA NVARCHAR(MAX) NOT NULL,
    AKTIF_MI BIT NOT NULL DEFAULT 1,
    CONSTRAINT PK_KATEGORILER PRIMARY KEY (ID)
);
GO

-- YAZARLAR (Authors)
CREATE TABLE YAZARLAR (
    ID INT IDENTITY(1,1) NOT NULL,
    AD NVARCHAR(MAX) NOT NULL,
    SOYAD NVARCHAR(MAX) NOT NULL,
    EPOSTA NVARCHAR(MAX) NOT NULL,
    SIFRE NVARCHAR(MAX) NOT NULL,
    RESIM NVARCHAR(MAX) NOT NULL,
    AKTIF_MI BIT NOT NULL DEFAULT 1,
    CONSTRAINT PK_YAZARLAR PRIMARY KEY (ID)
);
GO

-- HABERLER (News Articles)
CREATE TABLE HABERLER (
    ID INT IDENTITY(1,1) NOT NULL,
    BASLIK NVARCHAR(MAX) NOT NULL,
    EKLEME_TARIHI DATETIME2 NOT NULL DEFAULT GETDATE(),
    YAZAR_ID INT NOT NULL,
    CATEGORY_ID INT NOT NULL,
    ICERIK NVARCHAR(MAX) NOT NULL,
    RESIM NVARCHAR(MAX) NOT NULL,
    VIDEO NVARCHAR(MAX) NOT NULL,
    GOSTERIM_SAYISI INT NOT NULL DEFAULT 0,
    AKTIF_MI BIT NOT NULL DEFAULT 1,
    CONSTRAINT PK_HABERLER PRIMARY KEY (ID),
    CONSTRAINT FK_HABERLER_YAZARLAR FOREIGN KEY (YAZAR_ID) REFERENCES YAZARLAR(ID) ON DELETE CASCADE,
    CONSTRAINT FK_HABERLER_KATEGORILER FOREIGN KEY (CATEGORY_ID) REFERENCES KATEGORILER(ID) ON DELETE CASCADE
);
GO

-- YORUMLAR (Comments)
CREATE TABLE YORUMLAR (
    ID INT IDENTITY(1,1) NOT NULL,
    AD NVARCHAR(MAX) NOT NULL,
    SOYAD NVARCHAR(MAX) NOT NULL,
    EPOSTA NVARCHAR(MAX) NOT NULL,
    BASLIK NVARCHAR(MAX) NOT NULL,
    ICERIK NVARCHAR(MAX) NOT NULL,
    HABER_ID INT NOT NULL,
    EKLEME_TARIHI DATETIME2 NOT NULL DEFAULT GETDATE(),
    AKTIF_MI BIT NOT NULL DEFAULT 0,
    CONSTRAINT PK_YORUMLAR PRIMARY KEY (ID),
    CONSTRAINT FK_YORUMLAR_HABERLER FOREIGN KEY (HABER_ID) REFERENCES HABERLER(ID) ON DELETE CASCADE
);
GO

-- SLAYTLAR (Sliders/Carousel)
CREATE TABLE SLAYTLAR (
    ID INT IDENTITY(1,1) NOT NULL,
    BASLIK NVARCHAR(MAX) NOT NULL,
    ICERIK NVARCHAR(MAX) NOT NULL,
    HABER_ID INT NOT NULL,
    RESIM NVARCHAR(MAX) NOT NULL,
    AKTIF_MI BIT NOT NULL DEFAULT 1,
    CONSTRAINT PK_SLAYTLAR PRIMARY KEY (ID),
    CONSTRAINT FK_SLAYTLAR_HABERLER FOREIGN KEY (HABER_ID) REFERENCES HABERLER(ID) ON DELETE CASCADE
);
GO

-- Insert initial migration record
INSERT INTO __EFMigrationsHistory (MigrationId, ProductVersion)
VALUES ('20260123_InitialSqlServerMigration', '9.0.8');
GO

PRINT 'Database tables created successfully!';
PRINT 'Tables: KATEGORILER, YAZARLAR, HABERLER, YORUMLAR, SLAYTLAR';
GO
